### ISSUE TITLE
BUG: Excluded modules can exclude other modules accidentally

### ISSUE THREAD

**Issue by antonag32** [Vauxoo/pre-commit-vauxoo#102]
Example:

You have the following directories in your project's tree:

* sale
* sale_management
* sale_coupon

If you exclude `sale` from lints by adding it on `EXCLUDE_LINTS` in `variables.sh` pre-commit-vauxoo will generate
the following regex to exclude it:

`....|sale|...`

and this will exclude all three directories, I think the fix is simple and we just need to add a slash at the end of the module's name

`...|sale/|....`

**Comment by luisg123v** [comment]
@antonag32,

Hi agree on the solution.

Could you test it, please?

**Comment by antonag32** [comment]
Yes, I will work on it and add unit tests so we don't regress in the future.
