### ISSUE TITLE
Do not remove commas in scss files

### ISSUE THREAD

**Issue by rolandojduartem** [Vauxoo/pre-commit-vauxoo#18]
@moylop260 

The following issue happend in the recent [MR](https://git.vauxoo.com/vauxoo/instance/-/merge_requests/1388) where some commas like [this](https://git.vauxoo.com/vauxoo/instance/-/blob/0c61abc642306c81634f591b6b8152d0284dc31b/theme_vauxoo/static/src/scss/primary_variables.scss#L20) and [this](https://git.vauxoo.com/vauxoo/instance/-/blob/0c61abc642306c81634f591b6b8152d0284dc31b/theme_vauxoo/static/src/scss/primary_variables.scss#L35) were removed using pre-commit-vauxoo. Removing those commas caused this [traceback](https://gist.github.com/rolandojduartem/884c7704affce18460e5487687280326) which affect tour tests like [this](https://git.vauxoo.com/vauxoo-dev/instance/-/jobs/1008445#L5400). The problem was solved putting back those commas, but if you try to execute pre-commit-vauxoo again, it will remove those commas again. This is important for the new lint to avoid reformatted issues.

**Issue caused by removing commas:**

![Screenshot from 2022-08-24 15-34-32](https://user-images.githubusercontent.com/90422721/186529190-7b3d537b-93a0-41cd-b324-21faf6a4bf03.png)

![Screenshot from 2022-08-24 15-48-03](https://user-images.githubusercontent.com/90422721/186529564-39f7a497-492b-4154-aa84-2adb1c3be9fc.png)

**Resolved putting back commas (manually):**

![Screenshot from 2022-08-24 15-44-34](https://user-images.githubusercontent.com/90422721/186529372-f1ad66bd-63bb-42d6-8a29-2956cdd7fb26.png)

cc @luisg123v

**Comment by moylop260** [comment]
@rolandojduartem 

I can not reproduce it

# steps to reproduce

1. git clone --depth=1 -b 14.0-instance-black_isort_prettier-t54296-dev-rolando git@git.vauxoo.com:vauxoo-dev/instance.git
2. cd instance
3. PRECOMMIT_AUTOFIX=1 pre-commit-vauxoo
4. git status

# Expected

See the scss changes

# Saw

```txt
	modified:   CHANGELOG
	modified:   CONTRIBUTING.md
	modified:   check_doc.sh
	modified:   post-migration-script.sql
````


Could you describe better the steps to reproduce it, please?

**Comment by moylop260** [comment]
FYI I have already reproduced using the branch 14.0 sha b14bac0757807b24336930f886ba3693d3447587


After the configuration files were copied the issue is reproduced faster running the following command:
`pre-commit run prettier --color=always -c .pre-commit-config-autofix.yaml --file theme_vauxoo/static/src/scss/primary_variables.scss`

**Comment by moylop260** [comment]
@rolandojduartem 

Could you check if the output from https://github.com/Vauxoo/pre-commit-vauxoo/pull/19 is raising error too, please?

**Comment by rolandojduartem** [comment]
@moylop260 I followed this conversation in the PR FYI

**Comment by luisg123v** [comment]
I think this is because of https://github.com/prettier/prettier/issues/8855
