### ISSUE TITLE
[IMP] bring pre-commit feature in git commit command

### ISSUE THREAD

**Issue by fernandahf** [Vauxoo/pre-commit-vauxoo#37]
Currently, you can configure the `pre-commit` in you repo to run every time you run a `git commit ` automatically using `pre-commit install`, right now using `pre-commit-vauxoo`  you have to run manually every time when you do a commit to review the lints.

I think it could be a good improvement can use this way using pre-commit-vauxoo

**Comment by luisg123v** [comment]
@fernandahf do you mean when running `pre-commit-vauxoo`, the environment for pre-commit is automatically configured in the current repo? So when you commit the next time, it's run.

**Comment by moylop260** [comment]
FYI https://github.com/Vauxoo/pre-commit-vauxoo/pull/48
