### ISSUE TITLE
pre-commit-vauxoo: Apply it to the desired module only

### ISSUE THREAD

**Issue by rolandojduartem** [Vauxoo/pre-commit-vauxoo#4]
Hi, @moylop260,

I read that #2 was merged and now we can use it if we are in the repository's root or a specific folder of the project, but, the main idea is applying the pre-commit-vauxoo to a specific module, not all of them. pre-commit base use --files for this purpose. I do not know if this is part of point 2 or 3 of #1, but I think this a good feature to be considered.

**Expected behaviour (pre-commit base):**

![Screenshot from 2022-08-19 08-50-42](https://user-images.githubusercontent.com/90422721/185648894-72023f34-c0c6-473c-9380-db32a46b2ba2.png)

Kind regards.

cc @luisg123v

**Comment by moylop260** [comment]
@rolandojduartem 

In your screenshot we can not see the first command than you ran

But pre-commit is getting different results using this way

I mean, running `pre-commit run --all` is detecting a lint in the module `branch_accounting_report`

But running `pre-commit run --files branch_accounting_report/` even `pre-commit run --files branch_accounting_report/*` is not detecting any lint:
 - <img width="615" alt="Screen Shot 2022-08-19 at 10 43 01" src="https://user-images.githubusercontent.com/6644187/185656792-6e40a812-3e68-4d18-b64c-2590133a425f.png">

**Comment by moylop260** [comment]
I found a way to get all the files and send all them manually using `--files file1, file2, file3...`

This is my proposal

Could you test it, please?

 - https://github.com/Vauxoo/pre-commit-vauxoo/pull/5/commits/259b47dc64cd13b9c256f297ddad5f1008e043c5

Summary:
 - If you run `pre-commit-vauxoo` in the root path the command will use `--all`
 - else it will use `--files subpath/file1, subpath/file2...`
