### ISSUE TITLE
Exclude non-installable modules from checks

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/pre-commit-vauxoo#54]
IMHO modules marked as non-installable on the manifest should be excluded from all checks, unless explicitly specified (maybe by a param)

**Comment by moylop260** [comment]
We have a similar code to check if the module is installable from vxci:
 - https://git.vauxoo.com/devops/vxci/blob/0fac7890912743756dfb3654af682b805a0d56a7/vxci/get_addons.py#L53

We could re-use this way to autofill the exclude part in pre-commit-vauxoo:
 - https://github.com/Vauxoo/pre-commit-vauxoo/blob/a315c350a60bce21a0576463ee1fa0efa9c2cb2e/src/pre_commit_vauxoo/pre_commit_vauxoo.py#L41-L46

**Comment by moylop260** [comment]
> unless explicitly specified (maybe by a param)

I think case I could prefer to KISS

If you need to run pre-commit over an excluded path because of installable:False so you need to enable installable:True then run pre-commit-vauxoo

Something similar with `# pylint:disable=CHECK` comments

You need to remove them in order to re-enable it

**Comment by moylop260** [comment]
@antonag32

Could you help me to fix it, please?

I would like for this case don't refactor anything else only fix the particular issue and create new issue related to refactor if there are cases

What do you think?

**Comment by luisg123v** [comment]
> If you need to run pre-commit over an excluded path because of installable:False so you need to enable installable:True then run pre-commit-vauxoo

Great, I agree.

**Comment by antonag32** [comment]
Yes, I'll do it, just wondering why would there be a non-installable module? What is the use case for that? Also I think I don't have access to vxci so If I could get read access to see how it was implemented that would be great. Thanks

**Comment by moylop260** [comment]
@antonag32 

Thank you

I just have added permission to vxci

Please, confirm

A module could be non-installable if it has not been migrated yet

Or if you have a module installed in production but then deprecated in the same Odoo version

We use non-installable instead of deleting it to be able to uninstall it from production

**Comment by antonag32** [comment]
@moylop260 Yes I can see it now. Thanks for the explanation. I will start looking into this.
