### ISSUE TITLE
Show git diff if there were a reformatted from the CI

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/pre-commit-vauxoo#66]
Sometimes the local environment is different to CI

e.g. python version

So, the auto-fixes could be different between CI and local environment

Currently, if locally is not reformatting but CI there is not an easy way to fix it

A hard way is to install the same python version or check what is different (e.g. pre-commit-vauxoo version, black version, cache and so on)

Could be great to show a diff with the changes in order to apply it locally only if the auto-fixes did changes from the CI

Close to the following section:
 - https://github.com/Vauxoo/pre-commit-vauxoo/blob/914148ae4c8a6bfba3246451612de8283471f4b3/src/pre_commit_vauxoo/pre_commit_vauxoo.py#L253

In order to show a "git diff" output limited to 2k chars

**Comment by fernandahf** [comment]
@antonag32 

I'm working on this
