### ISSUE TITLE
Perform checks over new migration scripts

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/pre-commit-vauxoo#97]
Currently and for implementation purposes, we exclude migration scripts from [checks](https://github.com/Vauxoo/pre-commit-vauxoo/blob/7327afb26751a973f0c14f75b3526ae3d5d07ce8/src/pre_commit_vauxoo/cfg/.pre-commit-config.yaml#L19), for both lints and reformatting. That was did that way because lints were not considered in previous version of lint checker (before pre-commit-vauxoo), so we decided to disable them in order to avoid having to fix old lints on code that was already run and won't be run again.

Problem is, new code is also being excluded, which allows lines like [this one](https://git.vauxoo.com/vauxoo/instance/-/merge_requests/1495/diffs#78f8aec2bda3fd908c4a016d0efa6fb0e4a9e38e_0_18), which includes:
- Mixing tabs and spaces (tab is even between the line)
- Use double quotes (not a big deal)

New migration scripts should run at least lints, to prevent code issues like non-used variables being referenced.

Talking to @moylop260, we accorded we may enable all kind of checks for new migration scripts by considering versions >= 15.0, which we consider are recent enough to be fixed.

**Comment by antonag32** [comment]
@luisg123v If I understand correctly, anything in the `migrations` folder for a module that has a version >= 15.0 in it `__manifest__.py` is to be linted?

**Comment by luisg123v** [comment]
@antonag32 kind of, but you don't need to care about the manifest, just about paths.

I'd recommend, instead of excluding all migrations, excluding just: 1[0-4], i.e. 10, 11, 12, 13 and 14. We don't support customers below version 10.

**Comment by antonag32** [comment]
@luisg123v Ah I see, in that case it can probably be done simply by modifying the config file, in which case it would be hardcoded  but the benefit would be that no code will be written (i like that :laughing: ). I will try to accomplish it that way if no one objects to it.

**Comment by luisg123v** [comment]
@antonag32 Yes, it's the simpler way, it's harcoded anyway, go on with that approach
